quarkus:
  jib:
    platforms: linux/arm64/v8
  http:
    port: 8080

  rest-client:
    rest-service:
      url: http://${UFO_SERVER_URL}:${UFO_SERVER_PORT}
  grpc:
    server:
      use-separate-server: false
    clients:
      dataGrpc:
        host: ${UFO_SERVER_URL}
        port: ${UFO_SERVER_PORT}